Repository selfdevs/accountability-dashboard, pull requests merged in 2021-12, with the labels that each got.

#1 :memo: First contribution guidelines
  CONTRIBUTING.md
Labels: In discussion

#5 :building_construction: Front-end and back-end separation
  backend/mockdata.json
  frontend/.gitkeep
Labels: Review needed

#3 :memo: First try of contribution guidelines
  CONTRIBUTING.md
Labels: In discussion, Review needed

#13 :tada: Init React structure
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: Review needed

#4 📝 Added CODE_OF_CONDUCT template
  CODE_OF_CONDUCT.md
Labels: In discussion

#16 :memo: broken link to CONTRIBUTING.md
  README.md
Labels: Review needed

#15 :construction_worker: setup lint, test & security stage
  .github/workflows/frontend.yml
  frontend/package.json
  frontend/src/__tests__/App.spec.ts
  frontend/yarn.lock
Labels: Review needed

#19 :fire: Remove web vitals benchmark
  frontend/src/index.tsx
  frontend/src/reportWebVitals.js
Labels: Review needed

#14 :sparkles: New Sratchpad component
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Card/index.tsx
  frontend/src/components/Card/stylesheet.css
  frontend/src/components/ScratchPad/index.tsx
  frontend/src/components/ScratchPad/stylesheet.css
  frontend/src/mocks/scratchpad-data.json
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: Review needed

#18 :sparkles: Advanced version of ScratchPad with save
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/ScratchPad/ScrathPad.tsx
  frontend/src/components/ScratchPad/__tests__/ScratchPad.spec.tsx
  frontend/src/components/ScratchPad/__tests__/utils.spec.ts
  frontend/src/components/ScratchPad/constants.ts
  frontend/src/components/ScratchPad/hooks.ts
  frontend/src/components/ScratchPad/index.tsx
  frontend/src/components/ScratchPad/stylesheet.css
  frontend/src/components/ScratchPad/utils.ts
  frontend/src/mocks/scratchpad-data.json
  frontend/src/modules/storage/io.ts
  frontend/yarn.lock
Labels: Review needed

#20 :sparkles: Data displayed in a table
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/TableHeader.tsx
  frontend/src/components/Table/TableRow.tsx
  frontend/src/components/Table/hooks.ts
  frontend/src/components/Table/styles.css
  frontend/src/entities/Entry.ts
  frontend/src/mocks/table-data.ts
  frontend/yarn.lock
Labels: Review needed

#22 :sparkles: Add a router for the application
  frontend/package.json
  frontend/src/App.tsx
  frontend/yarn.lock
Labels: Review needed

#24 :lipstick: Refine the table design
  frontend/.eslintrc.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/Card/index.tsx
  frontend/src/components/Card/stylesheet.css
  frontend/src/components/ScratchPad/ScrathPad.tsx
  frontend/src/components/ScratchPad/stylesheet.css
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/TableRow.tsx
  frontend/src/components/Table/styles.css
Labels: Review needed

#25 :sparkles: Add a title
  frontend/src/App.css
  frontend/src/App.tsx
Labels: Review needed

#26 :sparkles: First social component version
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/Card/index.tsx
  frontend/src/components/Card/stylesheet.css
  frontend/src/components/ScratchPad/ScrathPad.tsx
  frontend/src/components/ScratchPad/stylesheet.css
  frontend/src/components/Social/Social.tsx
  frontend/src/components/Social/styles.css
  frontend/src/components/Table/Table.tsx
  frontend/src/components/Table/styles.css
  frontend/src/index.css
  frontend/src/pages/Dashboard.tsx
  frontend/src/pages/Homepage.tsx
  frontend/yarn.lock
Labels: Review needed

#28 :technologist: Deactivated linebreak rule for working on both, Windows and Unix
  frontend/.eslintrc.json
Labels: Review needed
