Repository selfdevs/accountability-dashboard, pull requests merged in 2022-02, with the labels that each got.

#82 :sparkles: Filter users without entries for the month
  backend/src/domains/entry/model.ts
  backend/src/domains/user/model.ts
  backend/src/routers/user.ts
Labels: Review needed, Beginner level

#87 ✨ Solves #63 #83 #86
  backend/.env
  backend/.gitignore
  backend/src/domains/discordCredentials/model.ts
  backend/src/domains/tokens/model.ts
  backend/src/routers/auth.ts
  backend/src/services/__tests__/authService.spec.ts
  backend/src/services/authService.ts
  backend/src/services/discordService.ts
  backend/yarn.lock
  frontend/package.json
  frontend/src/components/EditableTitle/EditableTitle.tsx
  frontend/src/components/EntryEditor/EntryEditor.tsx
  frontend/src/components/ScratchPad/hooks.ts
  frontend/src/components/Table/TableRow.tsx
  frontend/src/components/Table/hooks.ts
  frontend/src/contexts/Auth.tsx
  frontend/src/entities/Entry.ts
  frontend/src/entities/User.ts
  frontend/src/modules/http/axiosClient.ts
  frontend/src/modules/http/client.ts
  frontend/src/modules/storage/io.ts
  frontend/src/pages/Homepage.tsx
  frontend/yarn.lock
Labels: Review needed

#91 :bug: Fix webhook when day isn't created
  backend/src/services/discordService.ts
Labels: Review needed, Bug
